// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package config

import (
	"github.com/codyoss/wired/pkg/client"
	"github.com/codyoss/wired/pkg/rpc/http"
	"github.com/codyoss/wired/pkg/swapi"
	"github.com/gorilla/mux"
)

// Injectors from wire.go:

func InitializeRouter() *mux.Router {
	v := ProvideClientOptions()
	clientClient := client.New(v...)
	service := swapi.NewService(clientClient)
	cachedService := swapi.NewCachedService(service)
	swapiHandlerSet := http.NewSWAPIHandlerSet(cachedService)
	router := http.NewRouter(swapiHandlerSet)
	return router
}
